apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: color-service
    app.kubernetes.io/version: 2.0.0-SNAPSHOT
  name: color-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: color-service
